/*
Spartera API Documentation

Testing AssetsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package spartera

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_spartera_AssetsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AssetsAPIService CreateAssets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string

		resp, httpRes, err := apiClient.AssetsAPI.CreateAssets(context.Background(), companyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsAPIService CreateAssetsAnalyze", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var assetSlug string
		var companyHandle string

		resp, httpRes, err := apiClient.AssetsAPI.CreateAssetsAnalyze(context.Background(), assetSlug, companyHandle).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsAPIService CreateAssetsScanColumn", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string

		resp, httpRes, err := apiClient.AssetsAPI.CreateAssetsScanColumn(context.Background(), companyId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsAPIService CreateAssetsTest", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string

		resp, httpRes, err := apiClient.AssetsAPI.CreateAssetsTest(context.Background(), companyId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsAPIService DeleteAssets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string

		resp, httpRes, err := apiClient.AssetsAPI.DeleteAssets(context.Background(), companyId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsAPIService GetAssetsById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string

		resp, httpRes, err := apiClient.AssetsAPI.GetAssetsById(context.Background(), companyId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsAPIService GetAssetsById2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string

		resp, httpRes, err := apiClient.AssetsAPI.GetAssetsById2(context.Background(), companyId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsAPIService GetAssetsByIdAnalyze", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var assetSlug string
		var companyHandle string

		resp, httpRes, err := apiClient.AssetsAPI.GetAssetsByIdAnalyze(context.Background(), assetSlug, companyHandle).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsAPIService GetAssetsByIdInfoschema", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string

		resp, httpRes, err := apiClient.AssetsAPI.GetAssetsByIdInfoschema(context.Background(), companyId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsAPIService GetAssetsByIdInfoschemaSave", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string

		resp, httpRes, err := apiClient.AssetsAPI.GetAssetsByIdInfoschemaSave(context.Background(), companyId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsAPIService GetAssetsByIdPredictedPrice", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string

		resp, httpRes, err := apiClient.AssetsAPI.GetAssetsByIdPredictedPrice(context.Background(), companyId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsAPIService GetAssetsByIdStatistics", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string

		resp, httpRes, err := apiClient.AssetsAPI.GetAssetsByIdStatistics(context.Background(), companyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsAPIService GetAssetsByIdTest", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string

		resp, httpRes, err := apiClient.AssetsAPI.GetAssetsByIdTest(context.Background(), companyId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsAPIService ListAssets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string

		resp, httpRes, err := apiClient.AssetsAPI.ListAssets(context.Background(), companyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsAPIService ListAssetsSearch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string

		resp, httpRes, err := apiClient.AssetsAPI.ListAssetsSearch(context.Background(), companyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsAPIService UpdateAssets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string

		resp, httpRes, err := apiClient.AssetsAPI.UpdateAssets(context.Background(), companyId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
