/*
Spartera API Documentation

Testing StorageEnginesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package spartera

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_spartera_StorageEnginesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StorageEnginesAPIService GetStorageEnginesById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var providerId string
		var engineId string

		resp, httpRes, err := apiClient.StorageEnginesAPI.GetStorageEnginesById(context.Background(), providerId, engineId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StorageEnginesAPIService ListStorageEngines", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var providerId string

		resp, httpRes, err := apiClient.StorageEnginesAPI.ListStorageEngines(context.Background(), providerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
