/*
Spartera API Documentation

Testing AssetPriceHistoryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package spartera

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_spartera_AssetPriceHistoryAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AssetPriceHistoryAPIService CreateAssetPriceHistory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string

		resp, httpRes, err := apiClient.AssetPriceHistoryAPI.CreateAssetPriceHistory(context.Background(), companyId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetPriceHistoryAPIService CreateAssetPriceHistoryPricesCalculateCredits", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string

		resp, httpRes, err := apiClient.AssetPriceHistoryAPI.CreateAssetPriceHistoryPricesCalculateCredits(context.Background(), companyId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetPriceHistoryAPIService CreateAssetPriceHistoryPricesDiscount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string

		resp, httpRes, err := apiClient.AssetPriceHistoryAPI.CreateAssetPriceHistoryPricesDiscount(context.Background(), companyId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetPriceHistoryAPIService DeleteAssetPriceHistory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string
		var aphId string

		resp, httpRes, err := apiClient.AssetPriceHistoryAPI.DeleteAssetPriceHistory(context.Background(), companyId, assetId, aphId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetPriceHistoryAPIService GetAssetPriceHistoryById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string

		resp, httpRes, err := apiClient.AssetPriceHistoryAPI.GetAssetPriceHistoryById(context.Background(), companyId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetPriceHistoryAPIService GetAssetPriceHistoryByIdAssetsPrices", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string
		var aphId string

		resp, httpRes, err := apiClient.AssetPriceHistoryAPI.GetAssetPriceHistoryByIdAssetsPrices(context.Background(), companyId, assetId, aphId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetPriceHistoryAPIService GetAssetPriceHistoryByIdPricesActive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string

		resp, httpRes, err := apiClient.AssetPriceHistoryAPI.GetAssetPriceHistoryByIdPricesActive(context.Background(), companyId, assetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetPriceHistoryAPIService UpdateAssetPriceHistory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var assetId string
		var aphId string

		resp, httpRes, err := apiClient.AssetPriceHistoryAPI.UpdateAssetPriceHistory(context.Background(), companyId, assetId, aphId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
