/*
Spartera API Documentation

Testing ConnectionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package spartera

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_spartera_ConnectionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ConnectionsAPIService CreateConnections", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string

		resp, httpRes, err := apiClient.ConnectionsAPI.CreateConnections(context.Background(), companyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConnectionsAPIService DeleteConnections", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var connectionId string

		resp, httpRes, err := apiClient.ConnectionsAPI.DeleteConnections(context.Background(), companyId, connectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConnectionsAPIService GetConnectionsById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var connectionId string

		resp, httpRes, err := apiClient.ConnectionsAPI.GetConnectionsById(context.Background(), companyId, connectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConnectionsAPIService GetConnectionsById2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var connectionId string

		resp, httpRes, err := apiClient.ConnectionsAPI.GetConnectionsById2(context.Background(), companyId, connectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConnectionsAPIService GetConnectionsByIdInfoschema", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var connectionId string

		resp, httpRes, err := apiClient.ConnectionsAPI.GetConnectionsByIdInfoschema(context.Background(), companyId, connectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConnectionsAPIService ListConnections", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string

		resp, httpRes, err := apiClient.ConnectionsAPI.ListConnections(context.Background(), companyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConnectionsAPIService UpdateConnections", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string
		var connectionId string

		resp, httpRes, err := apiClient.ConnectionsAPI.UpdateConnections(context.Background(), companyId, connectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
