/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 0.0.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sparteraapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompaniesCompanyIdConnectionsConnectionIdDelete200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompaniesCompanyIdConnectionsConnectionIdDelete200Response{}

// CompaniesCompanyIdConnectionsConnectionIdDelete200Response struct for CompaniesCompanyIdConnectionsConnectionIdDelete200Response
type CompaniesCompanyIdConnectionsConnectionIdDelete200Response struct {
	// Response status message
	Message string `json:"message"`
	Data CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData `json:"data"`
}

type _CompaniesCompanyIdConnectionsConnectionIdDelete200Response CompaniesCompanyIdConnectionsConnectionIdDelete200Response

// NewCompaniesCompanyIdConnectionsConnectionIdDelete200Response instantiates a new CompaniesCompanyIdConnectionsConnectionIdDelete200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompaniesCompanyIdConnectionsConnectionIdDelete200Response(message string, data CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) *CompaniesCompanyIdConnectionsConnectionIdDelete200Response {
	this := CompaniesCompanyIdConnectionsConnectionIdDelete200Response{}
	this.Message = message
	this.Data = data
	return &this
}

// NewCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseWithDefaults instantiates a new CompaniesCompanyIdConnectionsConnectionIdDelete200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseWithDefaults() *CompaniesCompanyIdConnectionsConnectionIdDelete200Response {
	this := CompaniesCompanyIdConnectionsConnectionIdDelete200Response{}
	return &this
}

// GetMessage returns the Message field value
func (o *CompaniesCompanyIdConnectionsConnectionIdDelete200Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *CompaniesCompanyIdConnectionsConnectionIdDelete200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *CompaniesCompanyIdConnectionsConnectionIdDelete200Response) SetMessage(v string) {
	o.Message = v
}

// GetData returns the Data field value
func (o *CompaniesCompanyIdConnectionsConnectionIdDelete200Response) GetData() CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData {
	if o == nil {
		var ret CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CompaniesCompanyIdConnectionsConnectionIdDelete200Response) GetDataOk() (*CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CompaniesCompanyIdConnectionsConnectionIdDelete200Response) SetData(v CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) {
	o.Data = v
}

func (o CompaniesCompanyIdConnectionsConnectionIdDelete200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompaniesCompanyIdConnectionsConnectionIdDelete200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CompaniesCompanyIdConnectionsConnectionIdDelete200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompaniesCompanyIdConnectionsConnectionIdDelete200Response := _CompaniesCompanyIdConnectionsConnectionIdDelete200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompaniesCompanyIdConnectionsConnectionIdDelete200Response)

	if err != nil {
		return err
	}

	*o = CompaniesCompanyIdConnectionsConnectionIdDelete200Response(varCompaniesCompanyIdConnectionsConnectionIdDelete200Response)

	return err
}

type NullableCompaniesCompanyIdConnectionsConnectionIdDelete200Response struct {
	value *CompaniesCompanyIdConnectionsConnectionIdDelete200Response
	isSet bool
}

func (v NullableCompaniesCompanyIdConnectionsConnectionIdDelete200Response) Get() *CompaniesCompanyIdConnectionsConnectionIdDelete200Response {
	return v.value
}

func (v *NullableCompaniesCompanyIdConnectionsConnectionIdDelete200Response) Set(val *CompaniesCompanyIdConnectionsConnectionIdDelete200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCompaniesCompanyIdConnectionsConnectionIdDelete200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCompaniesCompanyIdConnectionsConnectionIdDelete200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompaniesCompanyIdConnectionsConnectionIdDelete200Response(val *CompaniesCompanyIdConnectionsConnectionIdDelete200Response) *NullableCompaniesCompanyIdConnectionsConnectionIdDelete200Response {
	return &NullableCompaniesCompanyIdConnectionsConnectionIdDelete200Response{value: val, isSet: true}
}

func (v NullableCompaniesCompanyIdConnectionsConnectionIdDelete200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompaniesCompanyIdConnectionsConnectionIdDelete200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


