/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 1.24.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sparteraapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData{}

// CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData struct for CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData
type CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData struct {
	// ID of the deleted asset_price_history
	AphId string `json:"aph_id"`
}

type _CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData

// NewCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData instantiates a new CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData(aphId string) *CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData {
	this := CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData{}
	this.AphId = aphId
	return &this
}

// NewCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseDataWithDefaults instantiates a new CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseDataWithDefaults() *CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData {
	this := CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData{}
	return &this
}

// GetAphId returns the AphId field value
func (o *CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData) GetAphId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AphId
}

// GetAphIdOk returns a tuple with the AphId field value
// and a boolean to check if the value has been set.
func (o *CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData) GetAphIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AphId, true
}

// SetAphId sets field value
func (o *CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData) SetAphId(v string) {
	o.AphId = v
}

func (o CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["aph_id"] = o.AphId
	return toSerialize, nil
}

func (o *CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"aph_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData := _CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData)

	if err != nil {
		return err
	}

	*o = CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData(varCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData)

	return err
}

type NullableCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData struct {
	value *CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData
	isSet bool
}

func (v NullableCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData) Get() *CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData {
	return v.value
}

func (v *NullableCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData) Set(val *CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData(val *CompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData) *NullableCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData {
	return &NullableCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData{value: val, isSet: true}
}

func (v NullableCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompaniesCompanyIdAssetsAssetIdPricesAphIdDelete200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


