/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 0.0.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sparteraapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData{}

// CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData struct for CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData
type CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData struct {
	// ID of the created favorites
	FavoriteId string `json:"favorite_id"`
}

type _CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData

// NewCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData instantiates a new CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData(favoriteId string) *CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData {
	this := CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData{}
	this.FavoriteId = favoriteId
	return &this
}

// NewCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseDataWithDefaults instantiates a new CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseDataWithDefaults() *CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData {
	this := CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData{}
	return &this
}

// GetFavoriteId returns the FavoriteId field value
func (o *CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData) GetFavoriteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FavoriteId
}

// GetFavoriteIdOk returns a tuple with the FavoriteId field value
// and a boolean to check if the value has been set.
func (o *CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData) GetFavoriteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FavoriteId, true
}

// SetFavoriteId sets field value
func (o *CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData) SetFavoriteId(v string) {
	o.FavoriteId = v
}

func (o CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["favorite_id"] = o.FavoriteId
	return toSerialize, nil
}

func (o *CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"favorite_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData := _CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData)

	if err != nil {
		return err
	}

	*o = CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData(varCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData)

	return err
}

type NullableCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData struct {
	value *CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData
	isSet bool
}

func (v NullableCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData) Get() *CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData {
	return v.value
}

func (v *NullableCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData) Set(val *CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData(val *CompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData) *NullableCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData {
	return &NullableCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData{value: val, isSet: true}
}

func (v NullableCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompaniesCompanyIdUsersUserIdFavoritesPost200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


