/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 1.25.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spartera

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateCompanies200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCompanies200ResponseData{}

// UpdateCompanies200ResponseData struct for UpdateCompanies200ResponseData
type UpdateCompanies200ResponseData struct {
	// ID of the updated companies
	CompanyId string `json:"company_id"`
}

type _UpdateCompanies200ResponseData UpdateCompanies200ResponseData

// NewUpdateCompanies200ResponseData instantiates a new UpdateCompanies200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCompanies200ResponseData(companyId string) *UpdateCompanies200ResponseData {
	this := UpdateCompanies200ResponseData{}
	this.CompanyId = companyId
	return &this
}

// NewUpdateCompanies200ResponseDataWithDefaults instantiates a new UpdateCompanies200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCompanies200ResponseDataWithDefaults() *UpdateCompanies200ResponseData {
	this := UpdateCompanies200ResponseData{}
	return &this
}

// GetCompanyId returns the CompanyId field value
func (o *UpdateCompanies200ResponseData) GetCompanyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value
// and a boolean to check if the value has been set.
func (o *UpdateCompanies200ResponseData) GetCompanyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyId, true
}

// SetCompanyId sets field value
func (o *UpdateCompanies200ResponseData) SetCompanyId(v string) {
	o.CompanyId = v
}

func (o UpdateCompanies200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCompanies200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["company_id"] = o.CompanyId
	return toSerialize, nil
}

func (o *UpdateCompanies200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"company_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCompanies200ResponseData := _UpdateCompanies200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCompanies200ResponseData)

	if err != nil {
		return err
	}

	*o = UpdateCompanies200ResponseData(varUpdateCompanies200ResponseData)

	return err
}

type NullableUpdateCompanies200ResponseData struct {
	value *UpdateCompanies200ResponseData
	isSet bool
}

func (v NullableUpdateCompanies200ResponseData) Get() *UpdateCompanies200ResponseData {
	return v.value
}

func (v *NullableUpdateCompanies200ResponseData) Set(val *UpdateCompanies200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCompanies200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCompanies200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCompanies200ResponseData(val *UpdateCompanies200ResponseData) *NullableUpdateCompanies200ResponseData {
	return &NullableUpdateCompanies200ResponseData{value: val, isSet: true}
}

func (v NullableUpdateCompanies200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCompanies200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


