/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 1.25.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spartera

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AssetsInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetsInput{}

// AssetsInput Input schema for creating Asset
type AssetsInput struct {
	// References users.user_id — An individual user account within a company. See GET /users for valid values. Optional.
	UserId *string `json:"user_id,omitempty"`
	// References companies.company_id — A Spartera seller or buyer company account. See GET /companies for valid values. Required.
	CompanyId string `json:"company_id"`
	// Optional.
	ConnectionId *string `json:"connection_id,omitempty"`
	// References industries.industry_id — Available industry categories for asset classification. Based on US NAISC codes.. See GET /industries for valid values. Optional.
	IndustryId *int64 `json:"industry_id,omitempty"`
	// Primary use case for this asset, from clustering analysis
	AucId *int64 `json:"auc_id,omitempty"`
	// Optional identifier for routing to specific functions/models at seller endpoint. For GET: appended to URL path. For POST: included in JSON body.
	FunctionId *string `json:"function_id,omitempty"`
	// Approval status for AI-generated assets
	ApprovalStatus *string `json:"approval_status,omitempty"`
	// User who approved this asset for marketplace
	ApprovedByUserId *string `json:"approved_by_user_id,omitempty"`
	// When this asset was approved for marketplace
	ApprovedAt *time.Time `json:"approved_at,omitempty"`
	// Required.
	Name string `json:"name"`
	// Optional.
	Slug *string `json:"slug,omitempty"`
	// Optional.
	Description *string `json:"description,omitempty"`
	// Long-form HTML description for product pages and SEO
	DetailedDescription *string `json:"detailed_description,omitempty"`
	// Required. One of: MANUAL, AUTOMATIC.
	Source string `json:"source"`
	// Optional. One of: CALCULATION, VISUALIZATION, DATA.
	AssetType *string `json:"asset_type,omitempty"`
	// Stores database table schema data including columns, types, and metadata
	AssetSchema map[string]interface{} `json:"asset_schema,omitempty"`
	// Optional.
	Tags *string `json:"tags,omitempty"`
	// Short code for tera.ac URL shortener (e.g., 'f78zq1')
	ShortCode *string `json:"short_code,omitempty"`
	// Semicolon or comma-separated list of domains restricted from accessing this asset
	RestrictedDomains *string `json:"restricted_domains,omitempty"`
	// Optional.
	SqlLogic *string `json:"sql_logic,omitempty"`
	// Optional.
	SourceSchemaName *string `json:"source_schema_name,omitempty"`
	// Optional.
	SourceTableName *string `json:"source_table_name,omitempty"`
	// Required.
	SellInMarketplace *bool `json:"sell_in_marketplace,omitempty"`
	// Whether this asset requires customization before use
	RequireCustomization *bool `json:"require_customization,omitempty"`
	// Optional. One of: PLOTLY, MATPLOTLIB, SEABORN.
	VizChartLibrary *string `json:"viz_chart_library,omitempty"`
	// Optional. One of: LINE, BAR, PIE, DOUGHNUT, POLAR, … (8 total).
	VizChartType *string `json:"viz_chart_type,omitempty"`
	// Optional.
	VizDepVarColName *string `json:"viz_dep_var_col_name,omitempty"`
	// Optional.
	VizIndepVarColName *string `json:"viz_indep_var_col_name,omitempty"`
	// Optional.
	VizSizeColName *string `json:"viz_size_col_name,omitempty"`
	// Optional.
	VizColorColName *string `json:"viz_color_col_name,omitempty"`
	// Optional. One of: No Aggregation, Sum, Average, Count, Minimum, … (6 total).
	VizDataAggregation *string `json:"viz_data_aggregation,omitempty"`
	// Optional. One of: No Sorting, Ascending, Descending.
	VizSortDirection *string `json:"viz_sort_direction,omitempty"`
	// Optional.
	VizDataLimit *int64 `json:"viz_data_limit,omitempty"`
	// Optional. One of: Default, Sequential, Diverging, Categorical, Monochrome, … (8 total).
	VizColorScheme *string `json:"viz_color_scheme,omitempty"`
	// Show/hide chart legend
	VizShowLegend *bool `json:"viz_show_legend,omitempty"`
	// Show/hide grid lines
	VizShowGrid *bool `json:"viz_show_grid,omitempty"`
	// Show trendline for scatter/line charts
	VizShowTrendline *bool `json:"viz_show_trendline,omitempty"`
	// Enable smoothing for line charts
	VizLineSmoothing *bool `json:"viz_line_smoothing,omitempty"`
	// Stack bars instead of grouping
	VizBarStacked *bool `json:"viz_bar_stacked,omitempty"`
	// Whether data_limit shows TOP or BOTTOM N
	VizFilterDirection *string `json:"viz_filter_direction,omitempty"`
	// Required.
	AllowParams *bool `json:"allow_params,omitempty"`
	// Required.
	AcceptTerms *bool `json:"accept_terms,omitempty"`
	// Optional.
	Cached *bool `json:"cached,omitempty"`
	// Optional.
	Schedule *string `json:"schedule,omitempty"`
	// Optional.
	NextRun *time.Time `json:"next_run,omitempty"`
	// Start date of the data time period covered
	DataTimePeriodStart *time.Time `json:"data_time_period_start,omitempty"`
	// End date of the data time period covered
	DataTimePeriodEnd *time.Time `json:"data_time_period_end,omitempty"`
	// Type of geographic coverage
	GeographicCoverageType *string `json:"geographic_coverage_type,omitempty"`
	// Specific regions/countries covered (e.g., 'United States, Canada, Mexico')
	GeographicCoverageDetails *string `json:"geographic_coverage_details,omitempty"`
	// How often the source data is refreshed
	DataSourceRefreshFrequency *string `json:"data_source_refresh_frequency,omitempty"`
	// When the source data was last refreshed
	DataSourceLastRefreshed *time.Time `json:"data_source_last_refreshed,omitempty"`
	// Number of requests allowed per period (e.g., 100)
	RateLimitNumber *int64 `json:"rate_limit_number,omitempty"`
	// Time period for rate limiting (second, minute, hour, day)
	RateLimitPeriod *string `json:"rate_limit_period,omitempty"`
	// Granularity level for rate limiting (USER, COMPANY, IP)
	RateLimitGranularity *string `json:"rate_limit_granularity,omitempty"`
}

type _AssetsInput AssetsInput

// NewAssetsInput instantiates a new AssetsInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetsInput(companyId string, name string, source string) *AssetsInput {
	this := AssetsInput{}
	this.CompanyId = companyId
	this.Name = name
	this.Source = source
	return &this
}

// NewAssetsInputWithDefaults instantiates a new AssetsInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetsInputWithDefaults() *AssetsInput {
	this := AssetsInput{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *AssetsInput) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *AssetsInput) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *AssetsInput) SetUserId(v string) {
	o.UserId = &v
}

// GetCompanyId returns the CompanyId field value
func (o *AssetsInput) GetCompanyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetCompanyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyId, true
}

// SetCompanyId sets field value
func (o *AssetsInput) SetCompanyId(v string) {
	o.CompanyId = v
}

// GetConnectionId returns the ConnectionId field value if set, zero value otherwise.
func (o *AssetsInput) GetConnectionId() string {
	if o == nil || IsNil(o.ConnectionId) {
		var ret string
		return ret
	}
	return *o.ConnectionId
}

// GetConnectionIdOk returns a tuple with the ConnectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetConnectionIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConnectionId) {
		return nil, false
	}
	return o.ConnectionId, true
}

// HasConnectionId returns a boolean if a field has been set.
func (o *AssetsInput) HasConnectionId() bool {
	if o != nil && !IsNil(o.ConnectionId) {
		return true
	}

	return false
}

// SetConnectionId gets a reference to the given string and assigns it to the ConnectionId field.
func (o *AssetsInput) SetConnectionId(v string) {
	o.ConnectionId = &v
}

// GetIndustryId returns the IndustryId field value if set, zero value otherwise.
func (o *AssetsInput) GetIndustryId() int64 {
	if o == nil || IsNil(o.IndustryId) {
		var ret int64
		return ret
	}
	return *o.IndustryId
}

// GetIndustryIdOk returns a tuple with the IndustryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetIndustryIdOk() (*int64, bool) {
	if o == nil || IsNil(o.IndustryId) {
		return nil, false
	}
	return o.IndustryId, true
}

// HasIndustryId returns a boolean if a field has been set.
func (o *AssetsInput) HasIndustryId() bool {
	if o != nil && !IsNil(o.IndustryId) {
		return true
	}

	return false
}

// SetIndustryId gets a reference to the given int64 and assigns it to the IndustryId field.
func (o *AssetsInput) SetIndustryId(v int64) {
	o.IndustryId = &v
}

// GetAucId returns the AucId field value if set, zero value otherwise.
func (o *AssetsInput) GetAucId() int64 {
	if o == nil || IsNil(o.AucId) {
		var ret int64
		return ret
	}
	return *o.AucId
}

// GetAucIdOk returns a tuple with the AucId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetAucIdOk() (*int64, bool) {
	if o == nil || IsNil(o.AucId) {
		return nil, false
	}
	return o.AucId, true
}

// HasAucId returns a boolean if a field has been set.
func (o *AssetsInput) HasAucId() bool {
	if o != nil && !IsNil(o.AucId) {
		return true
	}

	return false
}

// SetAucId gets a reference to the given int64 and assigns it to the AucId field.
func (o *AssetsInput) SetAucId(v int64) {
	o.AucId = &v
}

// GetFunctionId returns the FunctionId field value if set, zero value otherwise.
func (o *AssetsInput) GetFunctionId() string {
	if o == nil || IsNil(o.FunctionId) {
		var ret string
		return ret
	}
	return *o.FunctionId
}

// GetFunctionIdOk returns a tuple with the FunctionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetFunctionIdOk() (*string, bool) {
	if o == nil || IsNil(o.FunctionId) {
		return nil, false
	}
	return o.FunctionId, true
}

// HasFunctionId returns a boolean if a field has been set.
func (o *AssetsInput) HasFunctionId() bool {
	if o != nil && !IsNil(o.FunctionId) {
		return true
	}

	return false
}

// SetFunctionId gets a reference to the given string and assigns it to the FunctionId field.
func (o *AssetsInput) SetFunctionId(v string) {
	o.FunctionId = &v
}

// GetApprovalStatus returns the ApprovalStatus field value if set, zero value otherwise.
func (o *AssetsInput) GetApprovalStatus() string {
	if o == nil || IsNil(o.ApprovalStatus) {
		var ret string
		return ret
	}
	return *o.ApprovalStatus
}

// GetApprovalStatusOk returns a tuple with the ApprovalStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetApprovalStatusOk() (*string, bool) {
	if o == nil || IsNil(o.ApprovalStatus) {
		return nil, false
	}
	return o.ApprovalStatus, true
}

// HasApprovalStatus returns a boolean if a field has been set.
func (o *AssetsInput) HasApprovalStatus() bool {
	if o != nil && !IsNil(o.ApprovalStatus) {
		return true
	}

	return false
}

// SetApprovalStatus gets a reference to the given string and assigns it to the ApprovalStatus field.
func (o *AssetsInput) SetApprovalStatus(v string) {
	o.ApprovalStatus = &v
}

// GetApprovedByUserId returns the ApprovedByUserId field value if set, zero value otherwise.
func (o *AssetsInput) GetApprovedByUserId() string {
	if o == nil || IsNil(o.ApprovedByUserId) {
		var ret string
		return ret
	}
	return *o.ApprovedByUserId
}

// GetApprovedByUserIdOk returns a tuple with the ApprovedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetApprovedByUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.ApprovedByUserId) {
		return nil, false
	}
	return o.ApprovedByUserId, true
}

// HasApprovedByUserId returns a boolean if a field has been set.
func (o *AssetsInput) HasApprovedByUserId() bool {
	if o != nil && !IsNil(o.ApprovedByUserId) {
		return true
	}

	return false
}

// SetApprovedByUserId gets a reference to the given string and assigns it to the ApprovedByUserId field.
func (o *AssetsInput) SetApprovedByUserId(v string) {
	o.ApprovedByUserId = &v
}

// GetApprovedAt returns the ApprovedAt field value if set, zero value otherwise.
func (o *AssetsInput) GetApprovedAt() time.Time {
	if o == nil || IsNil(o.ApprovedAt) {
		var ret time.Time
		return ret
	}
	return *o.ApprovedAt
}

// GetApprovedAtOk returns a tuple with the ApprovedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetApprovedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ApprovedAt) {
		return nil, false
	}
	return o.ApprovedAt, true
}

// HasApprovedAt returns a boolean if a field has been set.
func (o *AssetsInput) HasApprovedAt() bool {
	if o != nil && !IsNil(o.ApprovedAt) {
		return true
	}

	return false
}

// SetApprovedAt gets a reference to the given time.Time and assigns it to the ApprovedAt field.
func (o *AssetsInput) SetApprovedAt(v time.Time) {
	o.ApprovedAt = &v
}

// GetName returns the Name field value
func (o *AssetsInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AssetsInput) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *AssetsInput) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *AssetsInput) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *AssetsInput) SetSlug(v string) {
	o.Slug = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AssetsInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AssetsInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AssetsInput) SetDescription(v string) {
	o.Description = &v
}

// GetDetailedDescription returns the DetailedDescription field value if set, zero value otherwise.
func (o *AssetsInput) GetDetailedDescription() string {
	if o == nil || IsNil(o.DetailedDescription) {
		var ret string
		return ret
	}
	return *o.DetailedDescription
}

// GetDetailedDescriptionOk returns a tuple with the DetailedDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetDetailedDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.DetailedDescription) {
		return nil, false
	}
	return o.DetailedDescription, true
}

// HasDetailedDescription returns a boolean if a field has been set.
func (o *AssetsInput) HasDetailedDescription() bool {
	if o != nil && !IsNil(o.DetailedDescription) {
		return true
	}

	return false
}

// SetDetailedDescription gets a reference to the given string and assigns it to the DetailedDescription field.
func (o *AssetsInput) SetDetailedDescription(v string) {
	o.DetailedDescription = &v
}

// GetSource returns the Source field value
func (o *AssetsInput) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *AssetsInput) SetSource(v string) {
	o.Source = v
}

// GetAssetType returns the AssetType field value if set, zero value otherwise.
func (o *AssetsInput) GetAssetType() string {
	if o == nil || IsNil(o.AssetType) {
		var ret string
		return ret
	}
	return *o.AssetType
}

// GetAssetTypeOk returns a tuple with the AssetType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetAssetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AssetType) {
		return nil, false
	}
	return o.AssetType, true
}

// HasAssetType returns a boolean if a field has been set.
func (o *AssetsInput) HasAssetType() bool {
	if o != nil && !IsNil(o.AssetType) {
		return true
	}

	return false
}

// SetAssetType gets a reference to the given string and assigns it to the AssetType field.
func (o *AssetsInput) SetAssetType(v string) {
	o.AssetType = &v
}

// GetAssetSchema returns the AssetSchema field value if set, zero value otherwise.
func (o *AssetsInput) GetAssetSchema() map[string]interface{} {
	if o == nil || IsNil(o.AssetSchema) {
		var ret map[string]interface{}
		return ret
	}
	return o.AssetSchema
}

// GetAssetSchemaOk returns a tuple with the AssetSchema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetAssetSchemaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AssetSchema) {
		return map[string]interface{}{}, false
	}
	return o.AssetSchema, true
}

// HasAssetSchema returns a boolean if a field has been set.
func (o *AssetsInput) HasAssetSchema() bool {
	if o != nil && !IsNil(o.AssetSchema) {
		return true
	}

	return false
}

// SetAssetSchema gets a reference to the given map[string]interface{} and assigns it to the AssetSchema field.
func (o *AssetsInput) SetAssetSchema(v map[string]interface{}) {
	o.AssetSchema = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *AssetsInput) GetTags() string {
	if o == nil || IsNil(o.Tags) {
		var ret string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetTagsOk() (*string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *AssetsInput) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given string and assigns it to the Tags field.
func (o *AssetsInput) SetTags(v string) {
	o.Tags = &v
}

// GetShortCode returns the ShortCode field value if set, zero value otherwise.
func (o *AssetsInput) GetShortCode() string {
	if o == nil || IsNil(o.ShortCode) {
		var ret string
		return ret
	}
	return *o.ShortCode
}

// GetShortCodeOk returns a tuple with the ShortCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetShortCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ShortCode) {
		return nil, false
	}
	return o.ShortCode, true
}

// HasShortCode returns a boolean if a field has been set.
func (o *AssetsInput) HasShortCode() bool {
	if o != nil && !IsNil(o.ShortCode) {
		return true
	}

	return false
}

// SetShortCode gets a reference to the given string and assigns it to the ShortCode field.
func (o *AssetsInput) SetShortCode(v string) {
	o.ShortCode = &v
}

// GetRestrictedDomains returns the RestrictedDomains field value if set, zero value otherwise.
func (o *AssetsInput) GetRestrictedDomains() string {
	if o == nil || IsNil(o.RestrictedDomains) {
		var ret string
		return ret
	}
	return *o.RestrictedDomains
}

// GetRestrictedDomainsOk returns a tuple with the RestrictedDomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetRestrictedDomainsOk() (*string, bool) {
	if o == nil || IsNil(o.RestrictedDomains) {
		return nil, false
	}
	return o.RestrictedDomains, true
}

// HasRestrictedDomains returns a boolean if a field has been set.
func (o *AssetsInput) HasRestrictedDomains() bool {
	if o != nil && !IsNil(o.RestrictedDomains) {
		return true
	}

	return false
}

// SetRestrictedDomains gets a reference to the given string and assigns it to the RestrictedDomains field.
func (o *AssetsInput) SetRestrictedDomains(v string) {
	o.RestrictedDomains = &v
}

// GetSqlLogic returns the SqlLogic field value if set, zero value otherwise.
func (o *AssetsInput) GetSqlLogic() string {
	if o == nil || IsNil(o.SqlLogic) {
		var ret string
		return ret
	}
	return *o.SqlLogic
}

// GetSqlLogicOk returns a tuple with the SqlLogic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetSqlLogicOk() (*string, bool) {
	if o == nil || IsNil(o.SqlLogic) {
		return nil, false
	}
	return o.SqlLogic, true
}

// HasSqlLogic returns a boolean if a field has been set.
func (o *AssetsInput) HasSqlLogic() bool {
	if o != nil && !IsNil(o.SqlLogic) {
		return true
	}

	return false
}

// SetSqlLogic gets a reference to the given string and assigns it to the SqlLogic field.
func (o *AssetsInput) SetSqlLogic(v string) {
	o.SqlLogic = &v
}

// GetSourceSchemaName returns the SourceSchemaName field value if set, zero value otherwise.
func (o *AssetsInput) GetSourceSchemaName() string {
	if o == nil || IsNil(o.SourceSchemaName) {
		var ret string
		return ret
	}
	return *o.SourceSchemaName
}

// GetSourceSchemaNameOk returns a tuple with the SourceSchemaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetSourceSchemaNameOk() (*string, bool) {
	if o == nil || IsNil(o.SourceSchemaName) {
		return nil, false
	}
	return o.SourceSchemaName, true
}

// HasSourceSchemaName returns a boolean if a field has been set.
func (o *AssetsInput) HasSourceSchemaName() bool {
	if o != nil && !IsNil(o.SourceSchemaName) {
		return true
	}

	return false
}

// SetSourceSchemaName gets a reference to the given string and assigns it to the SourceSchemaName field.
func (o *AssetsInput) SetSourceSchemaName(v string) {
	o.SourceSchemaName = &v
}

// GetSourceTableName returns the SourceTableName field value if set, zero value otherwise.
func (o *AssetsInput) GetSourceTableName() string {
	if o == nil || IsNil(o.SourceTableName) {
		var ret string
		return ret
	}
	return *o.SourceTableName
}

// GetSourceTableNameOk returns a tuple with the SourceTableName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetSourceTableNameOk() (*string, bool) {
	if o == nil || IsNil(o.SourceTableName) {
		return nil, false
	}
	return o.SourceTableName, true
}

// HasSourceTableName returns a boolean if a field has been set.
func (o *AssetsInput) HasSourceTableName() bool {
	if o != nil && !IsNil(o.SourceTableName) {
		return true
	}

	return false
}

// SetSourceTableName gets a reference to the given string and assigns it to the SourceTableName field.
func (o *AssetsInput) SetSourceTableName(v string) {
	o.SourceTableName = &v
}

// GetSellInMarketplace returns the SellInMarketplace field value if set, zero value otherwise.
func (o *AssetsInput) GetSellInMarketplace() bool {
	if o == nil || IsNil(o.SellInMarketplace) {
		var ret bool
		return ret
	}
	return *o.SellInMarketplace
}

// GetSellInMarketplaceOk returns a tuple with the SellInMarketplace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetSellInMarketplaceOk() (*bool, bool) {
	if o == nil || IsNil(o.SellInMarketplace) {
		return nil, false
	}
	return o.SellInMarketplace, true
}

// HasSellInMarketplace returns a boolean if a field has been set.
func (o *AssetsInput) HasSellInMarketplace() bool {
	if o != nil && !IsNil(o.SellInMarketplace) {
		return true
	}

	return false
}

// SetSellInMarketplace gets a reference to the given bool and assigns it to the SellInMarketplace field.
func (o *AssetsInput) SetSellInMarketplace(v bool) {
	o.SellInMarketplace = &v
}

// GetRequireCustomization returns the RequireCustomization field value if set, zero value otherwise.
func (o *AssetsInput) GetRequireCustomization() bool {
	if o == nil || IsNil(o.RequireCustomization) {
		var ret bool
		return ret
	}
	return *o.RequireCustomization
}

// GetRequireCustomizationOk returns a tuple with the RequireCustomization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetRequireCustomizationOk() (*bool, bool) {
	if o == nil || IsNil(o.RequireCustomization) {
		return nil, false
	}
	return o.RequireCustomization, true
}

// HasRequireCustomization returns a boolean if a field has been set.
func (o *AssetsInput) HasRequireCustomization() bool {
	if o != nil && !IsNil(o.RequireCustomization) {
		return true
	}

	return false
}

// SetRequireCustomization gets a reference to the given bool and assigns it to the RequireCustomization field.
func (o *AssetsInput) SetRequireCustomization(v bool) {
	o.RequireCustomization = &v
}

// GetVizChartLibrary returns the VizChartLibrary field value if set, zero value otherwise.
func (o *AssetsInput) GetVizChartLibrary() string {
	if o == nil || IsNil(o.VizChartLibrary) {
		var ret string
		return ret
	}
	return *o.VizChartLibrary
}

// GetVizChartLibraryOk returns a tuple with the VizChartLibrary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizChartLibraryOk() (*string, bool) {
	if o == nil || IsNil(o.VizChartLibrary) {
		return nil, false
	}
	return o.VizChartLibrary, true
}

// HasVizChartLibrary returns a boolean if a field has been set.
func (o *AssetsInput) HasVizChartLibrary() bool {
	if o != nil && !IsNil(o.VizChartLibrary) {
		return true
	}

	return false
}

// SetVizChartLibrary gets a reference to the given string and assigns it to the VizChartLibrary field.
func (o *AssetsInput) SetVizChartLibrary(v string) {
	o.VizChartLibrary = &v
}

// GetVizChartType returns the VizChartType field value if set, zero value otherwise.
func (o *AssetsInput) GetVizChartType() string {
	if o == nil || IsNil(o.VizChartType) {
		var ret string
		return ret
	}
	return *o.VizChartType
}

// GetVizChartTypeOk returns a tuple with the VizChartType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizChartTypeOk() (*string, bool) {
	if o == nil || IsNil(o.VizChartType) {
		return nil, false
	}
	return o.VizChartType, true
}

// HasVizChartType returns a boolean if a field has been set.
func (o *AssetsInput) HasVizChartType() bool {
	if o != nil && !IsNil(o.VizChartType) {
		return true
	}

	return false
}

// SetVizChartType gets a reference to the given string and assigns it to the VizChartType field.
func (o *AssetsInput) SetVizChartType(v string) {
	o.VizChartType = &v
}

// GetVizDepVarColName returns the VizDepVarColName field value if set, zero value otherwise.
func (o *AssetsInput) GetVizDepVarColName() string {
	if o == nil || IsNil(o.VizDepVarColName) {
		var ret string
		return ret
	}
	return *o.VizDepVarColName
}

// GetVizDepVarColNameOk returns a tuple with the VizDepVarColName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizDepVarColNameOk() (*string, bool) {
	if o == nil || IsNil(o.VizDepVarColName) {
		return nil, false
	}
	return o.VizDepVarColName, true
}

// HasVizDepVarColName returns a boolean if a field has been set.
func (o *AssetsInput) HasVizDepVarColName() bool {
	if o != nil && !IsNil(o.VizDepVarColName) {
		return true
	}

	return false
}

// SetVizDepVarColName gets a reference to the given string and assigns it to the VizDepVarColName field.
func (o *AssetsInput) SetVizDepVarColName(v string) {
	o.VizDepVarColName = &v
}

// GetVizIndepVarColName returns the VizIndepVarColName field value if set, zero value otherwise.
func (o *AssetsInput) GetVizIndepVarColName() string {
	if o == nil || IsNil(o.VizIndepVarColName) {
		var ret string
		return ret
	}
	return *o.VizIndepVarColName
}

// GetVizIndepVarColNameOk returns a tuple with the VizIndepVarColName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizIndepVarColNameOk() (*string, bool) {
	if o == nil || IsNil(o.VizIndepVarColName) {
		return nil, false
	}
	return o.VizIndepVarColName, true
}

// HasVizIndepVarColName returns a boolean if a field has been set.
func (o *AssetsInput) HasVizIndepVarColName() bool {
	if o != nil && !IsNil(o.VizIndepVarColName) {
		return true
	}

	return false
}

// SetVizIndepVarColName gets a reference to the given string and assigns it to the VizIndepVarColName field.
func (o *AssetsInput) SetVizIndepVarColName(v string) {
	o.VizIndepVarColName = &v
}

// GetVizSizeColName returns the VizSizeColName field value if set, zero value otherwise.
func (o *AssetsInput) GetVizSizeColName() string {
	if o == nil || IsNil(o.VizSizeColName) {
		var ret string
		return ret
	}
	return *o.VizSizeColName
}

// GetVizSizeColNameOk returns a tuple with the VizSizeColName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizSizeColNameOk() (*string, bool) {
	if o == nil || IsNil(o.VizSizeColName) {
		return nil, false
	}
	return o.VizSizeColName, true
}

// HasVizSizeColName returns a boolean if a field has been set.
func (o *AssetsInput) HasVizSizeColName() bool {
	if o != nil && !IsNil(o.VizSizeColName) {
		return true
	}

	return false
}

// SetVizSizeColName gets a reference to the given string and assigns it to the VizSizeColName field.
func (o *AssetsInput) SetVizSizeColName(v string) {
	o.VizSizeColName = &v
}

// GetVizColorColName returns the VizColorColName field value if set, zero value otherwise.
func (o *AssetsInput) GetVizColorColName() string {
	if o == nil || IsNil(o.VizColorColName) {
		var ret string
		return ret
	}
	return *o.VizColorColName
}

// GetVizColorColNameOk returns a tuple with the VizColorColName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizColorColNameOk() (*string, bool) {
	if o == nil || IsNil(o.VizColorColName) {
		return nil, false
	}
	return o.VizColorColName, true
}

// HasVizColorColName returns a boolean if a field has been set.
func (o *AssetsInput) HasVizColorColName() bool {
	if o != nil && !IsNil(o.VizColorColName) {
		return true
	}

	return false
}

// SetVizColorColName gets a reference to the given string and assigns it to the VizColorColName field.
func (o *AssetsInput) SetVizColorColName(v string) {
	o.VizColorColName = &v
}

// GetVizDataAggregation returns the VizDataAggregation field value if set, zero value otherwise.
func (o *AssetsInput) GetVizDataAggregation() string {
	if o == nil || IsNil(o.VizDataAggregation) {
		var ret string
		return ret
	}
	return *o.VizDataAggregation
}

// GetVizDataAggregationOk returns a tuple with the VizDataAggregation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizDataAggregationOk() (*string, bool) {
	if o == nil || IsNil(o.VizDataAggregation) {
		return nil, false
	}
	return o.VizDataAggregation, true
}

// HasVizDataAggregation returns a boolean if a field has been set.
func (o *AssetsInput) HasVizDataAggregation() bool {
	if o != nil && !IsNil(o.VizDataAggregation) {
		return true
	}

	return false
}

// SetVizDataAggregation gets a reference to the given string and assigns it to the VizDataAggregation field.
func (o *AssetsInput) SetVizDataAggregation(v string) {
	o.VizDataAggregation = &v
}

// GetVizSortDirection returns the VizSortDirection field value if set, zero value otherwise.
func (o *AssetsInput) GetVizSortDirection() string {
	if o == nil || IsNil(o.VizSortDirection) {
		var ret string
		return ret
	}
	return *o.VizSortDirection
}

// GetVizSortDirectionOk returns a tuple with the VizSortDirection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizSortDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.VizSortDirection) {
		return nil, false
	}
	return o.VizSortDirection, true
}

// HasVizSortDirection returns a boolean if a field has been set.
func (o *AssetsInput) HasVizSortDirection() bool {
	if o != nil && !IsNil(o.VizSortDirection) {
		return true
	}

	return false
}

// SetVizSortDirection gets a reference to the given string and assigns it to the VizSortDirection field.
func (o *AssetsInput) SetVizSortDirection(v string) {
	o.VizSortDirection = &v
}

// GetVizDataLimit returns the VizDataLimit field value if set, zero value otherwise.
func (o *AssetsInput) GetVizDataLimit() int64 {
	if o == nil || IsNil(o.VizDataLimit) {
		var ret int64
		return ret
	}
	return *o.VizDataLimit
}

// GetVizDataLimitOk returns a tuple with the VizDataLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizDataLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.VizDataLimit) {
		return nil, false
	}
	return o.VizDataLimit, true
}

// HasVizDataLimit returns a boolean if a field has been set.
func (o *AssetsInput) HasVizDataLimit() bool {
	if o != nil && !IsNil(o.VizDataLimit) {
		return true
	}

	return false
}

// SetVizDataLimit gets a reference to the given int64 and assigns it to the VizDataLimit field.
func (o *AssetsInput) SetVizDataLimit(v int64) {
	o.VizDataLimit = &v
}

// GetVizColorScheme returns the VizColorScheme field value if set, zero value otherwise.
func (o *AssetsInput) GetVizColorScheme() string {
	if o == nil || IsNil(o.VizColorScheme) {
		var ret string
		return ret
	}
	return *o.VizColorScheme
}

// GetVizColorSchemeOk returns a tuple with the VizColorScheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizColorSchemeOk() (*string, bool) {
	if o == nil || IsNil(o.VizColorScheme) {
		return nil, false
	}
	return o.VizColorScheme, true
}

// HasVizColorScheme returns a boolean if a field has been set.
func (o *AssetsInput) HasVizColorScheme() bool {
	if o != nil && !IsNil(o.VizColorScheme) {
		return true
	}

	return false
}

// SetVizColorScheme gets a reference to the given string and assigns it to the VizColorScheme field.
func (o *AssetsInput) SetVizColorScheme(v string) {
	o.VizColorScheme = &v
}

// GetVizShowLegend returns the VizShowLegend field value if set, zero value otherwise.
func (o *AssetsInput) GetVizShowLegend() bool {
	if o == nil || IsNil(o.VizShowLegend) {
		var ret bool
		return ret
	}
	return *o.VizShowLegend
}

// GetVizShowLegendOk returns a tuple with the VizShowLegend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizShowLegendOk() (*bool, bool) {
	if o == nil || IsNil(o.VizShowLegend) {
		return nil, false
	}
	return o.VizShowLegend, true
}

// HasVizShowLegend returns a boolean if a field has been set.
func (o *AssetsInput) HasVizShowLegend() bool {
	if o != nil && !IsNil(o.VizShowLegend) {
		return true
	}

	return false
}

// SetVizShowLegend gets a reference to the given bool and assigns it to the VizShowLegend field.
func (o *AssetsInput) SetVizShowLegend(v bool) {
	o.VizShowLegend = &v
}

// GetVizShowGrid returns the VizShowGrid field value if set, zero value otherwise.
func (o *AssetsInput) GetVizShowGrid() bool {
	if o == nil || IsNil(o.VizShowGrid) {
		var ret bool
		return ret
	}
	return *o.VizShowGrid
}

// GetVizShowGridOk returns a tuple with the VizShowGrid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizShowGridOk() (*bool, bool) {
	if o == nil || IsNil(o.VizShowGrid) {
		return nil, false
	}
	return o.VizShowGrid, true
}

// HasVizShowGrid returns a boolean if a field has been set.
func (o *AssetsInput) HasVizShowGrid() bool {
	if o != nil && !IsNil(o.VizShowGrid) {
		return true
	}

	return false
}

// SetVizShowGrid gets a reference to the given bool and assigns it to the VizShowGrid field.
func (o *AssetsInput) SetVizShowGrid(v bool) {
	o.VizShowGrid = &v
}

// GetVizShowTrendline returns the VizShowTrendline field value if set, zero value otherwise.
func (o *AssetsInput) GetVizShowTrendline() bool {
	if o == nil || IsNil(o.VizShowTrendline) {
		var ret bool
		return ret
	}
	return *o.VizShowTrendline
}

// GetVizShowTrendlineOk returns a tuple with the VizShowTrendline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizShowTrendlineOk() (*bool, bool) {
	if o == nil || IsNil(o.VizShowTrendline) {
		return nil, false
	}
	return o.VizShowTrendline, true
}

// HasVizShowTrendline returns a boolean if a field has been set.
func (o *AssetsInput) HasVizShowTrendline() bool {
	if o != nil && !IsNil(o.VizShowTrendline) {
		return true
	}

	return false
}

// SetVizShowTrendline gets a reference to the given bool and assigns it to the VizShowTrendline field.
func (o *AssetsInput) SetVizShowTrendline(v bool) {
	o.VizShowTrendline = &v
}

// GetVizLineSmoothing returns the VizLineSmoothing field value if set, zero value otherwise.
func (o *AssetsInput) GetVizLineSmoothing() bool {
	if o == nil || IsNil(o.VizLineSmoothing) {
		var ret bool
		return ret
	}
	return *o.VizLineSmoothing
}

// GetVizLineSmoothingOk returns a tuple with the VizLineSmoothing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizLineSmoothingOk() (*bool, bool) {
	if o == nil || IsNil(o.VizLineSmoothing) {
		return nil, false
	}
	return o.VizLineSmoothing, true
}

// HasVizLineSmoothing returns a boolean if a field has been set.
func (o *AssetsInput) HasVizLineSmoothing() bool {
	if o != nil && !IsNil(o.VizLineSmoothing) {
		return true
	}

	return false
}

// SetVizLineSmoothing gets a reference to the given bool and assigns it to the VizLineSmoothing field.
func (o *AssetsInput) SetVizLineSmoothing(v bool) {
	o.VizLineSmoothing = &v
}

// GetVizBarStacked returns the VizBarStacked field value if set, zero value otherwise.
func (o *AssetsInput) GetVizBarStacked() bool {
	if o == nil || IsNil(o.VizBarStacked) {
		var ret bool
		return ret
	}
	return *o.VizBarStacked
}

// GetVizBarStackedOk returns a tuple with the VizBarStacked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizBarStackedOk() (*bool, bool) {
	if o == nil || IsNil(o.VizBarStacked) {
		return nil, false
	}
	return o.VizBarStacked, true
}

// HasVizBarStacked returns a boolean if a field has been set.
func (o *AssetsInput) HasVizBarStacked() bool {
	if o != nil && !IsNil(o.VizBarStacked) {
		return true
	}

	return false
}

// SetVizBarStacked gets a reference to the given bool and assigns it to the VizBarStacked field.
func (o *AssetsInput) SetVizBarStacked(v bool) {
	o.VizBarStacked = &v
}

// GetVizFilterDirection returns the VizFilterDirection field value if set, zero value otherwise.
func (o *AssetsInput) GetVizFilterDirection() string {
	if o == nil || IsNil(o.VizFilterDirection) {
		var ret string
		return ret
	}
	return *o.VizFilterDirection
}

// GetVizFilterDirectionOk returns a tuple with the VizFilterDirection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetVizFilterDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.VizFilterDirection) {
		return nil, false
	}
	return o.VizFilterDirection, true
}

// HasVizFilterDirection returns a boolean if a field has been set.
func (o *AssetsInput) HasVizFilterDirection() bool {
	if o != nil && !IsNil(o.VizFilterDirection) {
		return true
	}

	return false
}

// SetVizFilterDirection gets a reference to the given string and assigns it to the VizFilterDirection field.
func (o *AssetsInput) SetVizFilterDirection(v string) {
	o.VizFilterDirection = &v
}

// GetAllowParams returns the AllowParams field value if set, zero value otherwise.
func (o *AssetsInput) GetAllowParams() bool {
	if o == nil || IsNil(o.AllowParams) {
		var ret bool
		return ret
	}
	return *o.AllowParams
}

// GetAllowParamsOk returns a tuple with the AllowParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetAllowParamsOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowParams) {
		return nil, false
	}
	return o.AllowParams, true
}

// HasAllowParams returns a boolean if a field has been set.
func (o *AssetsInput) HasAllowParams() bool {
	if o != nil && !IsNil(o.AllowParams) {
		return true
	}

	return false
}

// SetAllowParams gets a reference to the given bool and assigns it to the AllowParams field.
func (o *AssetsInput) SetAllowParams(v bool) {
	o.AllowParams = &v
}

// GetAcceptTerms returns the AcceptTerms field value if set, zero value otherwise.
func (o *AssetsInput) GetAcceptTerms() bool {
	if o == nil || IsNil(o.AcceptTerms) {
		var ret bool
		return ret
	}
	return *o.AcceptTerms
}

// GetAcceptTermsOk returns a tuple with the AcceptTerms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetAcceptTermsOk() (*bool, bool) {
	if o == nil || IsNil(o.AcceptTerms) {
		return nil, false
	}
	return o.AcceptTerms, true
}

// HasAcceptTerms returns a boolean if a field has been set.
func (o *AssetsInput) HasAcceptTerms() bool {
	if o != nil && !IsNil(o.AcceptTerms) {
		return true
	}

	return false
}

// SetAcceptTerms gets a reference to the given bool and assigns it to the AcceptTerms field.
func (o *AssetsInput) SetAcceptTerms(v bool) {
	o.AcceptTerms = &v
}

// GetCached returns the Cached field value if set, zero value otherwise.
func (o *AssetsInput) GetCached() bool {
	if o == nil || IsNil(o.Cached) {
		var ret bool
		return ret
	}
	return *o.Cached
}

// GetCachedOk returns a tuple with the Cached field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetCachedOk() (*bool, bool) {
	if o == nil || IsNil(o.Cached) {
		return nil, false
	}
	return o.Cached, true
}

// HasCached returns a boolean if a field has been set.
func (o *AssetsInput) HasCached() bool {
	if o != nil && !IsNil(o.Cached) {
		return true
	}

	return false
}

// SetCached gets a reference to the given bool and assigns it to the Cached field.
func (o *AssetsInput) SetCached(v bool) {
	o.Cached = &v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *AssetsInput) GetSchedule() string {
	if o == nil || IsNil(o.Schedule) {
		var ret string
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetScheduleOk() (*string, bool) {
	if o == nil || IsNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *AssetsInput) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given string and assigns it to the Schedule field.
func (o *AssetsInput) SetSchedule(v string) {
	o.Schedule = &v
}

// GetNextRun returns the NextRun field value if set, zero value otherwise.
func (o *AssetsInput) GetNextRun() time.Time {
	if o == nil || IsNil(o.NextRun) {
		var ret time.Time
		return ret
	}
	return *o.NextRun
}

// GetNextRunOk returns a tuple with the NextRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetNextRunOk() (*time.Time, bool) {
	if o == nil || IsNil(o.NextRun) {
		return nil, false
	}
	return o.NextRun, true
}

// HasNextRun returns a boolean if a field has been set.
func (o *AssetsInput) HasNextRun() bool {
	if o != nil && !IsNil(o.NextRun) {
		return true
	}

	return false
}

// SetNextRun gets a reference to the given time.Time and assigns it to the NextRun field.
func (o *AssetsInput) SetNextRun(v time.Time) {
	o.NextRun = &v
}

// GetDataTimePeriodStart returns the DataTimePeriodStart field value if set, zero value otherwise.
func (o *AssetsInput) GetDataTimePeriodStart() time.Time {
	if o == nil || IsNil(o.DataTimePeriodStart) {
		var ret time.Time
		return ret
	}
	return *o.DataTimePeriodStart
}

// GetDataTimePeriodStartOk returns a tuple with the DataTimePeriodStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetDataTimePeriodStartOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DataTimePeriodStart) {
		return nil, false
	}
	return o.DataTimePeriodStart, true
}

// HasDataTimePeriodStart returns a boolean if a field has been set.
func (o *AssetsInput) HasDataTimePeriodStart() bool {
	if o != nil && !IsNil(o.DataTimePeriodStart) {
		return true
	}

	return false
}

// SetDataTimePeriodStart gets a reference to the given time.Time and assigns it to the DataTimePeriodStart field.
func (o *AssetsInput) SetDataTimePeriodStart(v time.Time) {
	o.DataTimePeriodStart = &v
}

// GetDataTimePeriodEnd returns the DataTimePeriodEnd field value if set, zero value otherwise.
func (o *AssetsInput) GetDataTimePeriodEnd() time.Time {
	if o == nil || IsNil(o.DataTimePeriodEnd) {
		var ret time.Time
		return ret
	}
	return *o.DataTimePeriodEnd
}

// GetDataTimePeriodEndOk returns a tuple with the DataTimePeriodEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetDataTimePeriodEndOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DataTimePeriodEnd) {
		return nil, false
	}
	return o.DataTimePeriodEnd, true
}

// HasDataTimePeriodEnd returns a boolean if a field has been set.
func (o *AssetsInput) HasDataTimePeriodEnd() bool {
	if o != nil && !IsNil(o.DataTimePeriodEnd) {
		return true
	}

	return false
}

// SetDataTimePeriodEnd gets a reference to the given time.Time and assigns it to the DataTimePeriodEnd field.
func (o *AssetsInput) SetDataTimePeriodEnd(v time.Time) {
	o.DataTimePeriodEnd = &v
}

// GetGeographicCoverageType returns the GeographicCoverageType field value if set, zero value otherwise.
func (o *AssetsInput) GetGeographicCoverageType() string {
	if o == nil || IsNil(o.GeographicCoverageType) {
		var ret string
		return ret
	}
	return *o.GeographicCoverageType
}

// GetGeographicCoverageTypeOk returns a tuple with the GeographicCoverageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetGeographicCoverageTypeOk() (*string, bool) {
	if o == nil || IsNil(o.GeographicCoverageType) {
		return nil, false
	}
	return o.GeographicCoverageType, true
}

// HasGeographicCoverageType returns a boolean if a field has been set.
func (o *AssetsInput) HasGeographicCoverageType() bool {
	if o != nil && !IsNil(o.GeographicCoverageType) {
		return true
	}

	return false
}

// SetGeographicCoverageType gets a reference to the given string and assigns it to the GeographicCoverageType field.
func (o *AssetsInput) SetGeographicCoverageType(v string) {
	o.GeographicCoverageType = &v
}

// GetGeographicCoverageDetails returns the GeographicCoverageDetails field value if set, zero value otherwise.
func (o *AssetsInput) GetGeographicCoverageDetails() string {
	if o == nil || IsNil(o.GeographicCoverageDetails) {
		var ret string
		return ret
	}
	return *o.GeographicCoverageDetails
}

// GetGeographicCoverageDetailsOk returns a tuple with the GeographicCoverageDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetGeographicCoverageDetailsOk() (*string, bool) {
	if o == nil || IsNil(o.GeographicCoverageDetails) {
		return nil, false
	}
	return o.GeographicCoverageDetails, true
}

// HasGeographicCoverageDetails returns a boolean if a field has been set.
func (o *AssetsInput) HasGeographicCoverageDetails() bool {
	if o != nil && !IsNil(o.GeographicCoverageDetails) {
		return true
	}

	return false
}

// SetGeographicCoverageDetails gets a reference to the given string and assigns it to the GeographicCoverageDetails field.
func (o *AssetsInput) SetGeographicCoverageDetails(v string) {
	o.GeographicCoverageDetails = &v
}

// GetDataSourceRefreshFrequency returns the DataSourceRefreshFrequency field value if set, zero value otherwise.
func (o *AssetsInput) GetDataSourceRefreshFrequency() string {
	if o == nil || IsNil(o.DataSourceRefreshFrequency) {
		var ret string
		return ret
	}
	return *o.DataSourceRefreshFrequency
}

// GetDataSourceRefreshFrequencyOk returns a tuple with the DataSourceRefreshFrequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetDataSourceRefreshFrequencyOk() (*string, bool) {
	if o == nil || IsNil(o.DataSourceRefreshFrequency) {
		return nil, false
	}
	return o.DataSourceRefreshFrequency, true
}

// HasDataSourceRefreshFrequency returns a boolean if a field has been set.
func (o *AssetsInput) HasDataSourceRefreshFrequency() bool {
	if o != nil && !IsNil(o.DataSourceRefreshFrequency) {
		return true
	}

	return false
}

// SetDataSourceRefreshFrequency gets a reference to the given string and assigns it to the DataSourceRefreshFrequency field.
func (o *AssetsInput) SetDataSourceRefreshFrequency(v string) {
	o.DataSourceRefreshFrequency = &v
}

// GetDataSourceLastRefreshed returns the DataSourceLastRefreshed field value if set, zero value otherwise.
func (o *AssetsInput) GetDataSourceLastRefreshed() time.Time {
	if o == nil || IsNil(o.DataSourceLastRefreshed) {
		var ret time.Time
		return ret
	}
	return *o.DataSourceLastRefreshed
}

// GetDataSourceLastRefreshedOk returns a tuple with the DataSourceLastRefreshed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetDataSourceLastRefreshedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DataSourceLastRefreshed) {
		return nil, false
	}
	return o.DataSourceLastRefreshed, true
}

// HasDataSourceLastRefreshed returns a boolean if a field has been set.
func (o *AssetsInput) HasDataSourceLastRefreshed() bool {
	if o != nil && !IsNil(o.DataSourceLastRefreshed) {
		return true
	}

	return false
}

// SetDataSourceLastRefreshed gets a reference to the given time.Time and assigns it to the DataSourceLastRefreshed field.
func (o *AssetsInput) SetDataSourceLastRefreshed(v time.Time) {
	o.DataSourceLastRefreshed = &v
}

// GetRateLimitNumber returns the RateLimitNumber field value if set, zero value otherwise.
func (o *AssetsInput) GetRateLimitNumber() int64 {
	if o == nil || IsNil(o.RateLimitNumber) {
		var ret int64
		return ret
	}
	return *o.RateLimitNumber
}

// GetRateLimitNumberOk returns a tuple with the RateLimitNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetRateLimitNumberOk() (*int64, bool) {
	if o == nil || IsNil(o.RateLimitNumber) {
		return nil, false
	}
	return o.RateLimitNumber, true
}

// HasRateLimitNumber returns a boolean if a field has been set.
func (o *AssetsInput) HasRateLimitNumber() bool {
	if o != nil && !IsNil(o.RateLimitNumber) {
		return true
	}

	return false
}

// SetRateLimitNumber gets a reference to the given int64 and assigns it to the RateLimitNumber field.
func (o *AssetsInput) SetRateLimitNumber(v int64) {
	o.RateLimitNumber = &v
}

// GetRateLimitPeriod returns the RateLimitPeriod field value if set, zero value otherwise.
func (o *AssetsInput) GetRateLimitPeriod() string {
	if o == nil || IsNil(o.RateLimitPeriod) {
		var ret string
		return ret
	}
	return *o.RateLimitPeriod
}

// GetRateLimitPeriodOk returns a tuple with the RateLimitPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetRateLimitPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.RateLimitPeriod) {
		return nil, false
	}
	return o.RateLimitPeriod, true
}

// HasRateLimitPeriod returns a boolean if a field has been set.
func (o *AssetsInput) HasRateLimitPeriod() bool {
	if o != nil && !IsNil(o.RateLimitPeriod) {
		return true
	}

	return false
}

// SetRateLimitPeriod gets a reference to the given string and assigns it to the RateLimitPeriod field.
func (o *AssetsInput) SetRateLimitPeriod(v string) {
	o.RateLimitPeriod = &v
}

// GetRateLimitGranularity returns the RateLimitGranularity field value if set, zero value otherwise.
func (o *AssetsInput) GetRateLimitGranularity() string {
	if o == nil || IsNil(o.RateLimitGranularity) {
		var ret string
		return ret
	}
	return *o.RateLimitGranularity
}

// GetRateLimitGranularityOk returns a tuple with the RateLimitGranularity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsInput) GetRateLimitGranularityOk() (*string, bool) {
	if o == nil || IsNil(o.RateLimitGranularity) {
		return nil, false
	}
	return o.RateLimitGranularity, true
}

// HasRateLimitGranularity returns a boolean if a field has been set.
func (o *AssetsInput) HasRateLimitGranularity() bool {
	if o != nil && !IsNil(o.RateLimitGranularity) {
		return true
	}

	return false
}

// SetRateLimitGranularity gets a reference to the given string and assigns it to the RateLimitGranularity field.
func (o *AssetsInput) SetRateLimitGranularity(v string) {
	o.RateLimitGranularity = &v
}

func (o AssetsInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetsInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	toSerialize["company_id"] = o.CompanyId
	if !IsNil(o.ConnectionId) {
		toSerialize["connection_id"] = o.ConnectionId
	}
	if !IsNil(o.IndustryId) {
		toSerialize["industry_id"] = o.IndustryId
	}
	if !IsNil(o.AucId) {
		toSerialize["auc_id"] = o.AucId
	}
	if !IsNil(o.FunctionId) {
		toSerialize["function_id"] = o.FunctionId
	}
	if !IsNil(o.ApprovalStatus) {
		toSerialize["approval_status"] = o.ApprovalStatus
	}
	if !IsNil(o.ApprovedByUserId) {
		toSerialize["approved_by_user_id"] = o.ApprovedByUserId
	}
	if !IsNil(o.ApprovedAt) {
		toSerialize["approved_at"] = o.ApprovedAt
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DetailedDescription) {
		toSerialize["detailed_description"] = o.DetailedDescription
	}
	toSerialize["source"] = o.Source
	if !IsNil(o.AssetType) {
		toSerialize["asset_type"] = o.AssetType
	}
	if !IsNil(o.AssetSchema) {
		toSerialize["asset_schema"] = o.AssetSchema
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.ShortCode) {
		toSerialize["short_code"] = o.ShortCode
	}
	if !IsNil(o.RestrictedDomains) {
		toSerialize["restricted_domains"] = o.RestrictedDomains
	}
	if !IsNil(o.SqlLogic) {
		toSerialize["sql_logic"] = o.SqlLogic
	}
	if !IsNil(o.SourceSchemaName) {
		toSerialize["source_schema_name"] = o.SourceSchemaName
	}
	if !IsNil(o.SourceTableName) {
		toSerialize["source_table_name"] = o.SourceTableName
	}
	if !IsNil(o.SellInMarketplace) {
		toSerialize["sell_in_marketplace"] = o.SellInMarketplace
	}
	if !IsNil(o.RequireCustomization) {
		toSerialize["require_customization"] = o.RequireCustomization
	}
	if !IsNil(o.VizChartLibrary) {
		toSerialize["viz_chart_library"] = o.VizChartLibrary
	}
	if !IsNil(o.VizChartType) {
		toSerialize["viz_chart_type"] = o.VizChartType
	}
	if !IsNil(o.VizDepVarColName) {
		toSerialize["viz_dep_var_col_name"] = o.VizDepVarColName
	}
	if !IsNil(o.VizIndepVarColName) {
		toSerialize["viz_indep_var_col_name"] = o.VizIndepVarColName
	}
	if !IsNil(o.VizSizeColName) {
		toSerialize["viz_size_col_name"] = o.VizSizeColName
	}
	if !IsNil(o.VizColorColName) {
		toSerialize["viz_color_col_name"] = o.VizColorColName
	}
	if !IsNil(o.VizDataAggregation) {
		toSerialize["viz_data_aggregation"] = o.VizDataAggregation
	}
	if !IsNil(o.VizSortDirection) {
		toSerialize["viz_sort_direction"] = o.VizSortDirection
	}
	if !IsNil(o.VizDataLimit) {
		toSerialize["viz_data_limit"] = o.VizDataLimit
	}
	if !IsNil(o.VizColorScheme) {
		toSerialize["viz_color_scheme"] = o.VizColorScheme
	}
	if !IsNil(o.VizShowLegend) {
		toSerialize["viz_show_legend"] = o.VizShowLegend
	}
	if !IsNil(o.VizShowGrid) {
		toSerialize["viz_show_grid"] = o.VizShowGrid
	}
	if !IsNil(o.VizShowTrendline) {
		toSerialize["viz_show_trendline"] = o.VizShowTrendline
	}
	if !IsNil(o.VizLineSmoothing) {
		toSerialize["viz_line_smoothing"] = o.VizLineSmoothing
	}
	if !IsNil(o.VizBarStacked) {
		toSerialize["viz_bar_stacked"] = o.VizBarStacked
	}
	if !IsNil(o.VizFilterDirection) {
		toSerialize["viz_filter_direction"] = o.VizFilterDirection
	}
	if !IsNil(o.AllowParams) {
		toSerialize["allow_params"] = o.AllowParams
	}
	if !IsNil(o.AcceptTerms) {
		toSerialize["accept_terms"] = o.AcceptTerms
	}
	if !IsNil(o.Cached) {
		toSerialize["cached"] = o.Cached
	}
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	if !IsNil(o.NextRun) {
		toSerialize["next_run"] = o.NextRun
	}
	if !IsNil(o.DataTimePeriodStart) {
		toSerialize["data_time_period_start"] = o.DataTimePeriodStart
	}
	if !IsNil(o.DataTimePeriodEnd) {
		toSerialize["data_time_period_end"] = o.DataTimePeriodEnd
	}
	if !IsNil(o.GeographicCoverageType) {
		toSerialize["geographic_coverage_type"] = o.GeographicCoverageType
	}
	if !IsNil(o.GeographicCoverageDetails) {
		toSerialize["geographic_coverage_details"] = o.GeographicCoverageDetails
	}
	if !IsNil(o.DataSourceRefreshFrequency) {
		toSerialize["data_source_refresh_frequency"] = o.DataSourceRefreshFrequency
	}
	if !IsNil(o.DataSourceLastRefreshed) {
		toSerialize["data_source_last_refreshed"] = o.DataSourceLastRefreshed
	}
	if !IsNil(o.RateLimitNumber) {
		toSerialize["rate_limit_number"] = o.RateLimitNumber
	}
	if !IsNil(o.RateLimitPeriod) {
		toSerialize["rate_limit_period"] = o.RateLimitPeriod
	}
	if !IsNil(o.RateLimitGranularity) {
		toSerialize["rate_limit_granularity"] = o.RateLimitGranularity
	}
	return toSerialize, nil
}

func (o *AssetsInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"company_id",
		"name",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssetsInput := _AssetsInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssetsInput)

	if err != nil {
		return err
	}

	*o = AssetsInput(varAssetsInput)

	return err
}

type NullableAssetsInput struct {
	value *AssetsInput
	isSet bool
}

func (v NullableAssetsInput) Get() *AssetsInput {
	return v.value
}

func (v *NullableAssetsInput) Set(val *AssetsInput) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetsInput) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetsInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetsInput(val *AssetsInput) *NullableAssetsInput {
	return &NullableAssetsInput{value: val, isSet: true}
}

func (v NullableAssetsInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetsInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


