/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 1.25.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spartera

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListConnections200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListConnections200Response{}

// ListConnections200Response struct for ListConnections200Response
type ListConnections200Response struct {
	// Response status message
	Message string `json:"message"`
	Data []Connections `json:"data"`
}

type _ListConnections200Response ListConnections200Response

// NewListConnections200Response instantiates a new ListConnections200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListConnections200Response(message string, data []Connections) *ListConnections200Response {
	this := ListConnections200Response{}
	this.Message = message
	this.Data = data
	return &this
}

// NewListConnections200ResponseWithDefaults instantiates a new ListConnections200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListConnections200ResponseWithDefaults() *ListConnections200Response {
	this := ListConnections200Response{}
	return &this
}

// GetMessage returns the Message field value
func (o *ListConnections200Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ListConnections200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ListConnections200Response) SetMessage(v string) {
	o.Message = v
}

// GetData returns the Data field value
func (o *ListConnections200Response) GetData() []Connections {
	if o == nil {
		var ret []Connections
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListConnections200Response) GetDataOk() ([]Connections, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListConnections200Response) SetData(v []Connections) {
	o.Data = v
}

func (o ListConnections200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListConnections200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ListConnections200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListConnections200Response := _ListConnections200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListConnections200Response)

	if err != nil {
		return err
	}

	*o = ListConnections200Response(varListConnections200Response)

	return err
}

type NullableListConnections200Response struct {
	value *ListConnections200Response
	isSet bool
}

func (v NullableListConnections200Response) Get() *ListConnections200Response {
	return v.value
}

func (v *NullableListConnections200Response) Set(val *ListConnections200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListConnections200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListConnections200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListConnections200Response(val *ListConnections200Response) *NullableListConnections200Response {
	return &NullableListConnections200Response{value: val, isSet: true}
}

func (v NullableListConnections200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListConnections200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


