/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 1.25.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spartera

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreatePostgenIntegrations200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePostgenIntegrations200ResponseData{}

// CreatePostgenIntegrations200ResponseData struct for CreatePostgenIntegrations200ResponseData
type CreatePostgenIntegrations200ResponseData struct {
	// ID of the created postgen_integrations
	IntegrationId string `json:"integration_id"`
}

type _CreatePostgenIntegrations200ResponseData CreatePostgenIntegrations200ResponseData

// NewCreatePostgenIntegrations200ResponseData instantiates a new CreatePostgenIntegrations200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePostgenIntegrations200ResponseData(integrationId string) *CreatePostgenIntegrations200ResponseData {
	this := CreatePostgenIntegrations200ResponseData{}
	this.IntegrationId = integrationId
	return &this
}

// NewCreatePostgenIntegrations200ResponseDataWithDefaults instantiates a new CreatePostgenIntegrations200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePostgenIntegrations200ResponseDataWithDefaults() *CreatePostgenIntegrations200ResponseData {
	this := CreatePostgenIntegrations200ResponseData{}
	return &this
}

// GetIntegrationId returns the IntegrationId field value
func (o *CreatePostgenIntegrations200ResponseData) GetIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
func (o *CreatePostgenIntegrations200ResponseData) GetIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationId, true
}

// SetIntegrationId sets field value
func (o *CreatePostgenIntegrations200ResponseData) SetIntegrationId(v string) {
	o.IntegrationId = v
}

func (o CreatePostgenIntegrations200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePostgenIntegrations200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["integration_id"] = o.IntegrationId
	return toSerialize, nil
}

func (o *CreatePostgenIntegrations200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"integration_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePostgenIntegrations200ResponseData := _CreatePostgenIntegrations200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePostgenIntegrations200ResponseData)

	if err != nil {
		return err
	}

	*o = CreatePostgenIntegrations200ResponseData(varCreatePostgenIntegrations200ResponseData)

	return err
}

type NullableCreatePostgenIntegrations200ResponseData struct {
	value *CreatePostgenIntegrations200ResponseData
	isSet bool
}

func (v NullableCreatePostgenIntegrations200ResponseData) Get() *CreatePostgenIntegrations200ResponseData {
	return v.value
}

func (v *NullableCreatePostgenIntegrations200ResponseData) Set(val *CreatePostgenIntegrations200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePostgenIntegrations200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePostgenIntegrations200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePostgenIntegrations200ResponseData(val *CreatePostgenIntegrations200ResponseData) *NullableCreatePostgenIntegrations200ResponseData {
	return &NullableCreatePostgenIntegrations200ResponseData{value: val, isSet: true}
}

func (v NullableCreatePostgenIntegrations200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePostgenIntegrations200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


