/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 1.24.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sparteraapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompaniesCompanyIdAnalyticsAssetsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompaniesCompanyIdAnalyticsAssetsGet200Response{}

// CompaniesCompanyIdAnalyticsAssetsGet200Response struct for CompaniesCompanyIdAnalyticsAssetsGet200Response
type CompaniesCompanyIdAnalyticsAssetsGet200Response struct {
	// Response status message
	Message string `json:"message"`
	Data []Companies `json:"data"`
}

type _CompaniesCompanyIdAnalyticsAssetsGet200Response CompaniesCompanyIdAnalyticsAssetsGet200Response

// NewCompaniesCompanyIdAnalyticsAssetsGet200Response instantiates a new CompaniesCompanyIdAnalyticsAssetsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompaniesCompanyIdAnalyticsAssetsGet200Response(message string, data []Companies) *CompaniesCompanyIdAnalyticsAssetsGet200Response {
	this := CompaniesCompanyIdAnalyticsAssetsGet200Response{}
	this.Message = message
	this.Data = data
	return &this
}

// NewCompaniesCompanyIdAnalyticsAssetsGet200ResponseWithDefaults instantiates a new CompaniesCompanyIdAnalyticsAssetsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompaniesCompanyIdAnalyticsAssetsGet200ResponseWithDefaults() *CompaniesCompanyIdAnalyticsAssetsGet200Response {
	this := CompaniesCompanyIdAnalyticsAssetsGet200Response{}
	return &this
}

// GetMessage returns the Message field value
func (o *CompaniesCompanyIdAnalyticsAssetsGet200Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *CompaniesCompanyIdAnalyticsAssetsGet200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *CompaniesCompanyIdAnalyticsAssetsGet200Response) SetMessage(v string) {
	o.Message = v
}

// GetData returns the Data field value
func (o *CompaniesCompanyIdAnalyticsAssetsGet200Response) GetData() []Companies {
	if o == nil {
		var ret []Companies
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CompaniesCompanyIdAnalyticsAssetsGet200Response) GetDataOk() ([]Companies, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CompaniesCompanyIdAnalyticsAssetsGet200Response) SetData(v []Companies) {
	o.Data = v
}

func (o CompaniesCompanyIdAnalyticsAssetsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompaniesCompanyIdAnalyticsAssetsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CompaniesCompanyIdAnalyticsAssetsGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompaniesCompanyIdAnalyticsAssetsGet200Response := _CompaniesCompanyIdAnalyticsAssetsGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompaniesCompanyIdAnalyticsAssetsGet200Response)

	if err != nil {
		return err
	}

	*o = CompaniesCompanyIdAnalyticsAssetsGet200Response(varCompaniesCompanyIdAnalyticsAssetsGet200Response)

	return err
}

type NullableCompaniesCompanyIdAnalyticsAssetsGet200Response struct {
	value *CompaniesCompanyIdAnalyticsAssetsGet200Response
	isSet bool
}

func (v NullableCompaniesCompanyIdAnalyticsAssetsGet200Response) Get() *CompaniesCompanyIdAnalyticsAssetsGet200Response {
	return v.value
}

func (v *NullableCompaniesCompanyIdAnalyticsAssetsGet200Response) Set(val *CompaniesCompanyIdAnalyticsAssetsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCompaniesCompanyIdAnalyticsAssetsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCompaniesCompanyIdAnalyticsAssetsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompaniesCompanyIdAnalyticsAssetsGet200Response(val *CompaniesCompanyIdAnalyticsAssetsGet200Response) *NullableCompaniesCompanyIdAnalyticsAssetsGet200Response {
	return &NullableCompaniesCompanyIdAnalyticsAssetsGet200Response{value: val, isSet: true}
}

func (v NullableCompaniesCompanyIdAnalyticsAssetsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompaniesCompanyIdAnalyticsAssetsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


