/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 1.25.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spartera

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteUsers200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUsers200ResponseData{}

// DeleteUsers200ResponseData struct for DeleteUsers200ResponseData
type DeleteUsers200ResponseData struct {
	// ID of the deleted users
	UserId string `json:"user_id"`
}

type _DeleteUsers200ResponseData DeleteUsers200ResponseData

// NewDeleteUsers200ResponseData instantiates a new DeleteUsers200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUsers200ResponseData(userId string) *DeleteUsers200ResponseData {
	this := DeleteUsers200ResponseData{}
	this.UserId = userId
	return &this
}

// NewDeleteUsers200ResponseDataWithDefaults instantiates a new DeleteUsers200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUsers200ResponseDataWithDefaults() *DeleteUsers200ResponseData {
	this := DeleteUsers200ResponseData{}
	return &this
}

// GetUserId returns the UserId field value
func (o *DeleteUsers200ResponseData) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *DeleteUsers200ResponseData) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *DeleteUsers200ResponseData) SetUserId(v string) {
	o.UserId = v
}

func (o DeleteUsers200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUsers200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *DeleteUsers200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteUsers200ResponseData := _DeleteUsers200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteUsers200ResponseData)

	if err != nil {
		return err
	}

	*o = DeleteUsers200ResponseData(varDeleteUsers200ResponseData)

	return err
}

type NullableDeleteUsers200ResponseData struct {
	value *DeleteUsers200ResponseData
	isSet bool
}

func (v NullableDeleteUsers200ResponseData) Get() *DeleteUsers200ResponseData {
	return v.value
}

func (v *NullableDeleteUsers200ResponseData) Set(val *DeleteUsers200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUsers200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUsers200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUsers200ResponseData(val *DeleteUsers200ResponseData) *NullableDeleteUsers200ResponseData {
	return &NullableDeleteUsers200ResponseData{value: val, isSet: true}
}

func (v NullableDeleteUsers200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUsers200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


