/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 1.24.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sparteraapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData{}

// CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData struct for CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData
type CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData struct {
	// ID of the deleted connections
	ConnectionId string `json:"connection_id"`
}

type _CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData

// NewCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData instantiates a new CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData(connectionId string) *CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData {
	this := CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData{}
	this.ConnectionId = connectionId
	return &this
}

// NewCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseDataWithDefaults instantiates a new CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseDataWithDefaults() *CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData {
	this := CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData{}
	return &this
}

// GetConnectionId returns the ConnectionId field value
func (o *CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) GetConnectionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionId
}

// GetConnectionIdOk returns a tuple with the ConnectionId field value
// and a boolean to check if the value has been set.
func (o *CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) GetConnectionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionId, true
}

// SetConnectionId sets field value
func (o *CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) SetConnectionId(v string) {
	o.ConnectionId = v
}

func (o CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connection_id"] = o.ConnectionId
	return toSerialize, nil
}

func (o *CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connection_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData := _CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData)

	if err != nil {
		return err
	}

	*o = CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData(varCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData)

	return err
}

type NullableCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData struct {
	value *CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData
	isSet bool
}

func (v NullableCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) Get() *CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData {
	return v.value
}

func (v *NullableCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) Set(val *CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData(val *CompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) *NullableCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData {
	return &NullableCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData{value: val, isSet: true}
}

func (v NullableCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompaniesCompanyIdConnectionsConnectionIdDelete200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


