/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 1.24.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sparteraapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData{}

// CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData struct for CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData
type CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData struct {
	// ID of the created alerts
	AlertId string `json:"alert_id"`
}

type _CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData

// NewCompaniesCompanyIdUsersUserIdAlertsPost200ResponseData instantiates a new CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompaniesCompanyIdUsersUserIdAlertsPost200ResponseData(alertId string) *CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData {
	this := CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData{}
	this.AlertId = alertId
	return &this
}

// NewCompaniesCompanyIdUsersUserIdAlertsPost200ResponseDataWithDefaults instantiates a new CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompaniesCompanyIdUsersUserIdAlertsPost200ResponseDataWithDefaults() *CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData {
	this := CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData{}
	return &this
}

// GetAlertId returns the AlertId field value
func (o *CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData) GetAlertId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AlertId
}

// GetAlertIdOk returns a tuple with the AlertId field value
// and a boolean to check if the value has been set.
func (o *CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData) GetAlertIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlertId, true
}

// SetAlertId sets field value
func (o *CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData) SetAlertId(v string) {
	o.AlertId = v
}

func (o CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["alert_id"] = o.AlertId
	return toSerialize, nil
}

func (o *CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"alert_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompaniesCompanyIdUsersUserIdAlertsPost200ResponseData := _CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompaniesCompanyIdUsersUserIdAlertsPost200ResponseData)

	if err != nil {
		return err
	}

	*o = CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData(varCompaniesCompanyIdUsersUserIdAlertsPost200ResponseData)

	return err
}

type NullableCompaniesCompanyIdUsersUserIdAlertsPost200ResponseData struct {
	value *CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData
	isSet bool
}

func (v NullableCompaniesCompanyIdUsersUserIdAlertsPost200ResponseData) Get() *CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData {
	return v.value
}

func (v *NullableCompaniesCompanyIdUsersUserIdAlertsPost200ResponseData) Set(val *CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCompaniesCompanyIdUsersUserIdAlertsPost200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCompaniesCompanyIdUsersUserIdAlertsPost200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompaniesCompanyIdUsersUserIdAlertsPost200ResponseData(val *CompaniesCompanyIdUsersUserIdAlertsPost200ResponseData) *NullableCompaniesCompanyIdUsersUserIdAlertsPost200ResponseData {
	return &NullableCompaniesCompanyIdUsersUserIdAlertsPost200ResponseData{value: val, isSet: true}
}

func (v NullableCompaniesCompanyIdUsersUserIdAlertsPost200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompaniesCompanyIdUsersUserIdAlertsPost200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


