/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 1.24.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sparteraapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobFunctionsInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobFunctionsInput{}

// JobFunctionsInput Input schema for creating JobFunction
type JobFunctionsInput struct {
	Name string `json:"name"`
}

type _JobFunctionsInput JobFunctionsInput

// NewJobFunctionsInput instantiates a new JobFunctionsInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobFunctionsInput(name string) *JobFunctionsInput {
	this := JobFunctionsInput{}
	this.Name = name
	return &this
}

// NewJobFunctionsInputWithDefaults instantiates a new JobFunctionsInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobFunctionsInputWithDefaults() *JobFunctionsInput {
	this := JobFunctionsInput{}
	return &this
}

// GetName returns the Name field value
func (o *JobFunctionsInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *JobFunctionsInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *JobFunctionsInput) SetName(v string) {
	o.Name = v
}

func (o JobFunctionsInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobFunctionsInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *JobFunctionsInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobFunctionsInput := _JobFunctionsInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobFunctionsInput)

	if err != nil {
		return err
	}

	*o = JobFunctionsInput(varJobFunctionsInput)

	return err
}

type NullableJobFunctionsInput struct {
	value *JobFunctionsInput
	isSet bool
}

func (v NullableJobFunctionsInput) Get() *JobFunctionsInput {
	return v.value
}

func (v *NullableJobFunctionsInput) Set(val *JobFunctionsInput) {
	v.value = val
	v.isSet = true
}

func (v NullableJobFunctionsInput) IsSet() bool {
	return v.isSet
}

func (v *NullableJobFunctionsInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobFunctionsInput(val *JobFunctionsInput) *NullableJobFunctionsInput {
	return &NullableJobFunctionsInput{value: val, isSet: true}
}

func (v NullableJobFunctionsInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobFunctionsInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


