/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 1.25.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spartera

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteApiKeys200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteApiKeys200Response{}

// DeleteApiKeys200Response struct for DeleteApiKeys200Response
type DeleteApiKeys200Response struct {
	// Response status message
	Message string `json:"message"`
	Data DeleteApiKeys200ResponseData `json:"data"`
}

type _DeleteApiKeys200Response DeleteApiKeys200Response

// NewDeleteApiKeys200Response instantiates a new DeleteApiKeys200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteApiKeys200Response(message string, data DeleteApiKeys200ResponseData) *DeleteApiKeys200Response {
	this := DeleteApiKeys200Response{}
	this.Message = message
	this.Data = data
	return &this
}

// NewDeleteApiKeys200ResponseWithDefaults instantiates a new DeleteApiKeys200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteApiKeys200ResponseWithDefaults() *DeleteApiKeys200Response {
	this := DeleteApiKeys200Response{}
	return &this
}

// GetMessage returns the Message field value
func (o *DeleteApiKeys200Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *DeleteApiKeys200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *DeleteApiKeys200Response) SetMessage(v string) {
	o.Message = v
}

// GetData returns the Data field value
func (o *DeleteApiKeys200Response) GetData() DeleteApiKeys200ResponseData {
	if o == nil {
		var ret DeleteApiKeys200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeleteApiKeys200Response) GetDataOk() (*DeleteApiKeys200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeleteApiKeys200Response) SetData(v DeleteApiKeys200ResponseData) {
	o.Data = v
}

func (o DeleteApiKeys200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteApiKeys200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeleteApiKeys200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteApiKeys200Response := _DeleteApiKeys200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteApiKeys200Response)

	if err != nil {
		return err
	}

	*o = DeleteApiKeys200Response(varDeleteApiKeys200Response)

	return err
}

type NullableDeleteApiKeys200Response struct {
	value *DeleteApiKeys200Response
	isSet bool
}

func (v NullableDeleteApiKeys200Response) Get() *DeleteApiKeys200Response {
	return v.value
}

func (v *NullableDeleteApiKeys200Response) Set(val *DeleteApiKeys200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteApiKeys200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteApiKeys200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteApiKeys200Response(val *DeleteApiKeys200Response) *NullableDeleteApiKeys200Response {
	return &NullableDeleteApiKeys200Response{value: val, isSet: true}
}

func (v NullableDeleteApiKeys200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteApiKeys200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


