/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 1.25.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spartera

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateEndpoints200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEndpoints200ResponseData{}

// UpdateEndpoints200ResponseData struct for UpdateEndpoints200ResponseData
type UpdateEndpoints200ResponseData struct {
	// ID of the updated endpoints
	EndpointId string `json:"endpoint_id"`
}

type _UpdateEndpoints200ResponseData UpdateEndpoints200ResponseData

// NewUpdateEndpoints200ResponseData instantiates a new UpdateEndpoints200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEndpoints200ResponseData(endpointId string) *UpdateEndpoints200ResponseData {
	this := UpdateEndpoints200ResponseData{}
	this.EndpointId = endpointId
	return &this
}

// NewUpdateEndpoints200ResponseDataWithDefaults instantiates a new UpdateEndpoints200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEndpoints200ResponseDataWithDefaults() *UpdateEndpoints200ResponseData {
	this := UpdateEndpoints200ResponseData{}
	return &this
}

// GetEndpointId returns the EndpointId field value
func (o *UpdateEndpoints200ResponseData) GetEndpointId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value
// and a boolean to check if the value has been set.
func (o *UpdateEndpoints200ResponseData) GetEndpointIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndpointId, true
}

// SetEndpointId sets field value
func (o *UpdateEndpoints200ResponseData) SetEndpointId(v string) {
	o.EndpointId = v
}

func (o UpdateEndpoints200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEndpoints200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["endpoint_id"] = o.EndpointId
	return toSerialize, nil
}

func (o *UpdateEndpoints200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endpoint_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateEndpoints200ResponseData := _UpdateEndpoints200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateEndpoints200ResponseData)

	if err != nil {
		return err
	}

	*o = UpdateEndpoints200ResponseData(varUpdateEndpoints200ResponseData)

	return err
}

type NullableUpdateEndpoints200ResponseData struct {
	value *UpdateEndpoints200ResponseData
	isSet bool
}

func (v NullableUpdateEndpoints200ResponseData) Get() *UpdateEndpoints200ResponseData {
	return v.value
}

func (v *NullableUpdateEndpoints200ResponseData) Set(val *UpdateEndpoints200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEndpoints200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEndpoints200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEndpoints200ResponseData(val *UpdateEndpoints200ResponseData) *NullableUpdateEndpoints200ResponseData {
	return &NullableUpdateEndpoints200ResponseData{value: val, isSet: true}
}

func (v NullableUpdateEndpoints200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEndpoints200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


