/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 1.25.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spartera

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetAssetsByIdAnalyze200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAssetsByIdAnalyze200Response{}

// GetAssetsByIdAnalyze200Response struct for GetAssetsByIdAnalyze200Response
type GetAssetsByIdAnalyze200Response struct {
	// Response status message
	Message string `json:"message"`
	Data Assets `json:"data"`
}

type _GetAssetsByIdAnalyze200Response GetAssetsByIdAnalyze200Response

// NewGetAssetsByIdAnalyze200Response instantiates a new GetAssetsByIdAnalyze200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAssetsByIdAnalyze200Response(message string, data Assets) *GetAssetsByIdAnalyze200Response {
	this := GetAssetsByIdAnalyze200Response{}
	this.Message = message
	this.Data = data
	return &this
}

// NewGetAssetsByIdAnalyze200ResponseWithDefaults instantiates a new GetAssetsByIdAnalyze200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAssetsByIdAnalyze200ResponseWithDefaults() *GetAssetsByIdAnalyze200Response {
	this := GetAssetsByIdAnalyze200Response{}
	return &this
}

// GetMessage returns the Message field value
func (o *GetAssetsByIdAnalyze200Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *GetAssetsByIdAnalyze200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *GetAssetsByIdAnalyze200Response) SetMessage(v string) {
	o.Message = v
}

// GetData returns the Data field value
func (o *GetAssetsByIdAnalyze200Response) GetData() Assets {
	if o == nil {
		var ret Assets
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetAssetsByIdAnalyze200Response) GetDataOk() (*Assets, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetAssetsByIdAnalyze200Response) SetData(v Assets) {
	o.Data = v
}

func (o GetAssetsByIdAnalyze200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAssetsByIdAnalyze200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetAssetsByIdAnalyze200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAssetsByIdAnalyze200Response := _GetAssetsByIdAnalyze200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetAssetsByIdAnalyze200Response)

	if err != nil {
		return err
	}

	*o = GetAssetsByIdAnalyze200Response(varGetAssetsByIdAnalyze200Response)

	return err
}

type NullableGetAssetsByIdAnalyze200Response struct {
	value *GetAssetsByIdAnalyze200Response
	isSet bool
}

func (v NullableGetAssetsByIdAnalyze200Response) Get() *GetAssetsByIdAnalyze200Response {
	return v.value
}

func (v *NullableGetAssetsByIdAnalyze200Response) Set(val *GetAssetsByIdAnalyze200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAssetsByIdAnalyze200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAssetsByIdAnalyze200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAssetsByIdAnalyze200Response(val *GetAssetsByIdAnalyze200Response) *NullableGetAssetsByIdAnalyze200Response {
	return &NullableGetAssetsByIdAnalyze200Response{value: val, isSet: true}
}

func (v NullableGetAssetsByIdAnalyze200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAssetsByIdAnalyze200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


