/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 0.0.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sparteraapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData{}

// CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData struct for CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData
type CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData struct {
	// ID of the updated connections
	ConnectionId string `json:"connection_id"`
}

type _CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData

// NewCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData instantiates a new CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData(connectionId string) *CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData {
	this := CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData{}
	this.ConnectionId = connectionId
	return &this
}

// NewCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseDataWithDefaults instantiates a new CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseDataWithDefaults() *CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData {
	this := CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData{}
	return &this
}

// GetConnectionId returns the ConnectionId field value
func (o *CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData) GetConnectionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionId
}

// GetConnectionIdOk returns a tuple with the ConnectionId field value
// and a boolean to check if the value has been set.
func (o *CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData) GetConnectionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConnectionId, true
}

// SetConnectionId sets field value
func (o *CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData) SetConnectionId(v string) {
	o.ConnectionId = v
}

func (o CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connection_id"] = o.ConnectionId
	return toSerialize, nil
}

func (o *CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connection_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData := _CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData)

	if err != nil {
		return err
	}

	*o = CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData(varCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData)

	return err
}

type NullableCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData struct {
	value *CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData
	isSet bool
}

func (v NullableCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData) Get() *CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData {
	return v.value
}

func (v *NullableCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData) Set(val *CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData(val *CompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData) *NullableCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData {
	return &NullableCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData{value: val, isSet: true}
}

func (v NullableCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompaniesCompanyIdConnectionsConnectionIdPatch200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


