/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 1.25.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spartera

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeletePosts200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeletePosts200Response{}

// DeletePosts200Response struct for DeletePosts200Response
type DeletePosts200Response struct {
	// Response status message
	Message string `json:"message"`
	Data DeletePosts200ResponseData `json:"data"`
}

type _DeletePosts200Response DeletePosts200Response

// NewDeletePosts200Response instantiates a new DeletePosts200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletePosts200Response(message string, data DeletePosts200ResponseData) *DeletePosts200Response {
	this := DeletePosts200Response{}
	this.Message = message
	this.Data = data
	return &this
}

// NewDeletePosts200ResponseWithDefaults instantiates a new DeletePosts200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletePosts200ResponseWithDefaults() *DeletePosts200Response {
	this := DeletePosts200Response{}
	return &this
}

// GetMessage returns the Message field value
func (o *DeletePosts200Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *DeletePosts200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *DeletePosts200Response) SetMessage(v string) {
	o.Message = v
}

// GetData returns the Data field value
func (o *DeletePosts200Response) GetData() DeletePosts200ResponseData {
	if o == nil {
		var ret DeletePosts200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeletePosts200Response) GetDataOk() (*DeletePosts200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeletePosts200Response) SetData(v DeletePosts200ResponseData) {
	o.Data = v
}

func (o DeletePosts200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletePosts200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeletePosts200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeletePosts200Response := _DeletePosts200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeletePosts200Response)

	if err != nil {
		return err
	}

	*o = DeletePosts200Response(varDeletePosts200Response)

	return err
}

type NullableDeletePosts200Response struct {
	value *DeletePosts200Response
	isSet bool
}

func (v NullableDeletePosts200Response) Get() *DeletePosts200Response {
	return v.value
}

func (v *NullableDeletePosts200Response) Set(val *DeletePosts200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletePosts200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletePosts200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletePosts200Response(val *DeletePosts200Response) *NullableDeletePosts200Response {
	return &NullableDeletePosts200Response{value: val, isSet: true}
}

func (v NullableDeletePosts200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletePosts200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


