/*
Spartera API Documentation

Auto-generated API documentation for REST services of the Spartera platform

API version: 1.25.0
Contact: support@spartera.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spartera

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateApiKeys200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateApiKeys200ResponseData{}

// CreateApiKeys200ResponseData struct for CreateApiKeys200ResponseData
type CreateApiKeys200ResponseData struct {
	// ID of the created api_keys
	ApiKeyId string `json:"api_key_id"`
}

type _CreateApiKeys200ResponseData CreateApiKeys200ResponseData

// NewCreateApiKeys200ResponseData instantiates a new CreateApiKeys200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateApiKeys200ResponseData(apiKeyId string) *CreateApiKeys200ResponseData {
	this := CreateApiKeys200ResponseData{}
	this.ApiKeyId = apiKeyId
	return &this
}

// NewCreateApiKeys200ResponseDataWithDefaults instantiates a new CreateApiKeys200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateApiKeys200ResponseDataWithDefaults() *CreateApiKeys200ResponseData {
	this := CreateApiKeys200ResponseData{}
	return &this
}

// GetApiKeyId returns the ApiKeyId field value
func (o *CreateApiKeys200ResponseData) GetApiKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKeyId
}

// GetApiKeyIdOk returns a tuple with the ApiKeyId field value
// and a boolean to check if the value has been set.
func (o *CreateApiKeys200ResponseData) GetApiKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKeyId, true
}

// SetApiKeyId sets field value
func (o *CreateApiKeys200ResponseData) SetApiKeyId(v string) {
	o.ApiKeyId = v
}

func (o CreateApiKeys200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateApiKeys200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["api_key_id"] = o.ApiKeyId
	return toSerialize, nil
}

func (o *CreateApiKeys200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"api_key_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateApiKeys200ResponseData := _CreateApiKeys200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateApiKeys200ResponseData)

	if err != nil {
		return err
	}

	*o = CreateApiKeys200ResponseData(varCreateApiKeys200ResponseData)

	return err
}

type NullableCreateApiKeys200ResponseData struct {
	value *CreateApiKeys200ResponseData
	isSet bool
}

func (v NullableCreateApiKeys200ResponseData) Get() *CreateApiKeys200ResponseData {
	return v.value
}

func (v *NullableCreateApiKeys200ResponseData) Set(val *CreateApiKeys200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApiKeys200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApiKeys200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApiKeys200ResponseData(val *CreateApiKeys200ResponseData) *NullableCreateApiKeys200ResponseData {
	return &NullableCreateApiKeys200ResponseData{value: val, isSet: true}
}

func (v NullableCreateApiKeys200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApiKeys200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


